#!/sbin/sh
rm -rf /system/addon.d/70-gapps.sh
rm -rf /system/addon.d/71-faceunlock.sh
rm -rf /system/addon.d/71-gapps-faceunlock.sh
rm -rf /system/addon.d/74-googlecamera.sh
rm -rf /system/addon.d/74-googlegallery.sh
rm -rf /system/addon.d/75-googlegallery.sh
rm -rf /system/addon.d/78-chromebrowser.sh
rm -rf /system/app/AmbientSensePrebuilt
rm -rf /system/app/AmbientSensePrebuilt.apk
rm -rf /system/app/AmbientSensePrebuilt.odex
rm -rf /system/app/AndroidForWork
rm -rf /system/app/AndroidForWork.apk
rm -rf /system/app/AndroidForWork.odex
rm -rf /system/app/AndroidMigratePrebuilt
rm -rf /system/app/AndroidMigratePrebuilt.apk
rm -rf /system/app/AndroidMigratePrebuilt.odex
rm -rf /system/app/AndroidPlatformServices
rm -rf /system/app/AndroidPlatformServices.apk
rm -rf /system/app/AndroidPlatformServices.odex
rm -rf /system/app/BackupRestoreConfirmation
rm -rf /system/app/BackupRestoreConfirmation.apk
rm -rf /system/app/BackupRestoreConfirmation.odex
rm -rf /system/app/Books
rm -rf /system/app/Books.apk
rm -rf /system/app/Books.odex
rm -rf /system/app/BooksPhone
rm -rf /system/app/BooksPhone.apk
rm -rf /system/app/BooksPhone.odex
rm -rf /system/app/BooksStub
rm -rf /system/app/BooksStub.apk
rm -rf /system/app/BooksStub.odex
rm -rf /system/app/BrowserProviderProxy
rm -rf /system/app/BrowserProviderProxy.apk
rm -rf /system/app/BrowserProviderProxy.odex
rm -rf /system/app/CalculatorGoogle
rm -rf /system/app/CalculatorGoogle.apk
rm -rf /system/app/CalculatorGoogle.odex
rm -rf /system/app/CalculatorGooglePrebuilt
rm -rf /system/app/CalculatorGooglePrebuilt.apk
rm -rf /system/app/CalculatorGooglePrebuilt.odex
rm -rf /system/app/Calendar
rm -rf /system/app/Calendar.apk
rm -rf /system/app/Calendar.odex
rm -rf /system/app/CalendarGoogle
rm -rf /system/app/CalendarGoogle.apk
rm -rf /system/app/CalendarGoogle.odex
rm -rf /system/app/CalendarGooglePrebuilt
rm -rf /system/app/CalendarGooglePrebuilt.apk
rm -rf /system/app/CalendarGooglePrebuilt.odex
rm -rf /system/app/CalendarProvider
rm -rf /system/app/CalendarProvider.apk
rm -rf /system/app/CalendarProvider.odex
rm -rf /system/app/CarHomeGoogle
rm -rf /system/app/CarHomeGoogle.apk
rm -rf /system/app/CarHomeGoogle.odex
rm -rf /system/app/CellBroadcastReceiver
rm -rf /system/app/CellBroadcastReceiver.apk
rm -rf /system/app/CellBroadcastReceiver.odex
rm -rf /system/app/Chrome
rm -rf /system/app/Chrome.apk
rm -rf /system/app/Chrome.odex
rm -rf /system/app/ChromeBookmarksSyncAdapter
rm -rf /system/app/ChromeBookmarksSyncAdapter.apk
rm -rf /system/app/ChromeBookmarksSyncAdapter.odex
rm -rf /system/app/CloudPrint
rm -rf /system/app/CloudPrint.apk
rm -rf /system/app/CloudPrint.odex
rm -rf /system/app/CloudPrint2
rm -rf /system/app/CloudPrint2.apk
rm -rf /system/app/CloudPrint2.odex
rm -rf /system/app/ConfigUpdater
rm -rf /system/app/ConfigUpdater.apk
rm -rf /system/app/ConfigUpdater.odex
rm -rf /system/app/ConnMO
rm -rf /system/app/ConnMO.apk
rm -rf /system/app/ConnMO.odex
rm -rf /system/app/Currents
rm -rf /system/app/Currents.apk
rm -rf /system/app/Currents.odex
rm -rf /system/app/DeskClockGoogle
rm -rf /system/app/DeskClockGoogle.apk
rm -rf /system/app/DeskClockGoogle.odex
rm -rf /system/app/DMAgent
rm -rf /system/app/DMAgent.apk
rm -rf /system/app/DMAgent.odex
rm -rf /system/app/Drive
rm -rf /system/app/Drive.apk
rm -rf /system/app/Drive.odex
rm -rf /system/app/Duo
rm -rf /system/app/Duo.apk
rm -rf /system/app/Duo.odex
rm -rf /system/app/EditorsDocs
rm -rf /system/app/EditorsDocs.apk
rm -rf /system/app/EditorsDocs.odex
rm -rf /system/app/EditorsDocsStub
rm -rf /system/app/EditorsDocsStub.apk
rm -rf /system/app/EditorsDocsStub.odex
rm -rf /system/app/EditorsSheets
rm -rf /system/app/EditorsSheets.apk
rm -rf /system/app/EditorsSheets.odex
rm -rf /system/app/EditorsSheetsStub
rm -rf /system/app/EditorsSheetsStub.apk
rm -rf /system/app/EditorsSheetsStub.odex
rm -rf /system/app/EditorsSlides
rm -rf /system/app/EditorsSlides.apk
rm -rf /system/app/EditorsSlides.odex
rm -rf /system/app/EditorsSlidesStub
rm -rf /system/app/EditorsSlidesStub.apk
rm -rf /system/app/EditorsSlidesStub.odex
rm -rf /system/app/EuiccGoogle
rm -rf /system/app/EuiccGoogle.apk
rm -rf /system/app/EuiccGoogle.odex
rm -rf /system/app/ExchangeServices
rm -rf /system/app/ExchangeServices.apk
rm -rf /system/app/ExchangeServices.odex
rm -rf /system/app/FaceLock
rm -rf /system/app/FaceLock.apk
rm -rf /system/app/FaceLock.odex
rm -rf /system/app/Finsky
rm -rf /system/app/Finsky.apk
rm -rf /system/app/Finsky.odex
rm -rf /system/app/FitnessPrebuilt
rm -rf /system/app/FitnessPrebuilt.apk
rm -rf /system/app/FitnessPrebuilt.odex
rm -rf /system/app/FOTAKill
rm -rf /system/app/FOTAKill.apk
rm -rf /system/app/FOTAKill.odex
rm -rf /system/app/GalleryGoogle
rm -rf /system/app/GalleryGoogle.apk
rm -rf /system/app/GalleryGoogle.odex
rm -rf /system/app/GCS
rm -rf /system/app/GCS.apk
rm -rf /system/app/GCS.odex
rm -rf /system/app/GenieWidget
rm -rf /system/app/GenieWidget.apk
rm -rf /system/app/GenieWidget.odex
rm -rf /system/app/Gmail
rm -rf /system/app/Gmail.apk
rm -rf /system/app/Gmail.odex
rm -rf /system/app/Gmail2
rm -rf /system/app/Gmail2.apk
rm -rf /system/app/Gmail2.odex
rm -rf /system/app/GmsCore
rm -rf /system/app/GmsCore.apk
rm -rf /system/app/GmsCore.odex
rm -rf /system/app/GmsCore_update
rm -rf /system/app/GmsCore_update.apk
rm -rf /system/app/GmsCore_update.odex
rm -rf /system/app/GmsCoreSetupPrebuilt
rm -rf /system/app/GmsCoreSetupPrebuilt.apk
rm -rf /system/app/GmsCoreSetupPrebuilt.odex
rm -rf /system/app/GoogleBackupTransport
rm -rf /system/app/GoogleBackupTransport.apk
rm -rf /system/app/GoogleBackupTransport.odex
rm -rf /system/app/GoogleCalendar
rm -rf /system/app/GoogleCalendar.apk
rm -rf /system/app/GoogleCalendar.odex
rm -rf /system/app/GoogleCalendarSyncAdapter
rm -rf /system/app/GoogleCalendarSyncAdapter.apk
rm -rf /system/app/GoogleCalendarSyncAdapter.odex
rm -rf /system/app/GoogleCamera
rm -rf /system/app/GoogleCamera.apk
rm -rf /system/app/GoogleCamera.odex
rm -rf /system/app/GoogleCameraLegacy
rm -rf /system/app/GoogleCameraLegacy.apk
rm -rf /system/app/GoogleCameraLegacy.odex
rm -rf /system/app/GoogleCloudPrint
rm -rf /system/app/GoogleCloudPrint.apk
rm -rf /system/app/GoogleCloudPrint.odex
rm -rf /system/app/GoogleContacts
rm -rf /system/app/GoogleContacts.apk
rm -rf /system/app/GoogleContacts.odex
rm -rf /system/app/GoogleContactsSyncAdapter
rm -rf /system/app/GoogleContactsSyncAdapter.apk
rm -rf /system/app/GoogleContactsSyncAdapter.odex
rm -rf /system/app/GoogleDialer
rm -rf /system/app/GoogleDialer.apk
rm -rf /system/app/GoogleDialer.odex
rm -rf /system/app/GoogleEars
rm -rf /system/app/GoogleEars.apk
rm -rf /system/app/GoogleEars.odex
rm -rf /system/app/GoogleEarth
rm -rf /system/app/GoogleEarth.apk
rm -rf /system/app/GoogleEarth.odex
rm -rf /system/app/GoogleExtServices
rm -rf /system/app/GoogleExtServices.apk
rm -rf /system/app/GoogleExtServices.odex
rm -rf /system/app/GoogleExtShared
rm -rf /system/app/GoogleExtShared.apk
rm -rf /system/app/GoogleExtShared.odex
rm -rf /system/app/GoogleFeedback
rm -rf /system/app/GoogleFeedback.apk
rm -rf /system/app/GoogleFeedback.odex
rm -rf /system/app/GoogleHangouts
rm -rf /system/app/GoogleHangouts.apk
rm -rf /system/app/GoogleHangouts.odex
rm -rf /system/app/GoogleHindiIME
rm -rf /system/app/GoogleHindiIME.apk
rm -rf /system/app/GoogleHindiIME.odex
rm -rf /system/app/GoogleHome
rm -rf /system/app/GoogleHome.apk
rm -rf /system/app/GoogleHome.odex
rm -rf /system/app/GoogleJapaneseInput
rm -rf /system/app/GoogleJapaneseInput.apk
rm -rf /system/app/GoogleJapaneseInput.odex
rm -rf /system/app/GoogleKeep
rm -rf /system/app/GoogleKeep.apk
rm -rf /system/app/GoogleKeep.odex
rm -rf /system/app/GoogleLatinIme
rm -rf /system/app/GoogleLatinIme.apk
rm -rf /system/app/GoogleLatinIme.odex
rm -rf /system/app/GoogleLoginService
rm -rf /system/app/GoogleLoginService.apk
rm -rf /system/app/GoogleLoginService.odex
rm -rf /system/app/GoogleMusic
rm -rf /system/app/GoogleMusic.apk
rm -rf /system/app/GoogleMusic.odex
rm -rf /system/app/GoogleNow
rm -rf /system/app/GoogleNow.apk
rm -rf /system/app/GoogleNow.odex
rm -rf /system/app/GoogleNowVoiceSearch
rm -rf /system/app/GoogleNowVoiceSearch.apk
rm -rf /system/app/GoogleNowVoiceSearch.odex
rm -rf /system/app/GoogleOneTimeInitializer
rm -rf /system/app/GoogleOneTimeInitializer.apk
rm -rf /system/app/GoogleOneTimeInitializer.odex
rm -rf /system/app/GooglePartnerSetup
rm -rf /system/app/GooglePartnerSetup.apk
rm -rf /system/app/GooglePartnerSetup.odex
rm -rf /system/app/GooglePinyinIME
rm -rf /system/app/GooglePinyinIME.apk
rm -rf /system/app/GooglePinyinIME.odex
rm -rf /system/app/GooglePlay
rm -rf /system/app/GooglePlay.apk
rm -rf /system/app/GooglePlay.odex
rm -rf /system/app/GooglePlus
rm -rf /system/app/GooglePlus.apk
rm -rf /system/app/GooglePlus.odex
rm -rf /system/app/GooglePrintRecommendationService
rm -rf /system/app/GooglePrintRecommendationService.apk
rm -rf /system/app/GooglePrintRecommendationService.odex
rm -rf /system/app/GoogleQuickSearchBox
rm -rf /system/app/GoogleQuickSearchBox.apk
rm -rf /system/app/GoogleQuickSearchBox.odex
rm -rf /system/app/GoogleSearch
rm -rf /system/app/GoogleSearch.apk
rm -rf /system/app/GoogleSearch.odex
rm -rf /system/app/GoogleServicesFramework
rm -rf /system/app/GoogleServicesFramework.apk
rm -rf /system/app/GoogleServicesFramework.odex
rm -rf /system/app/GoogleTTS
rm -rf /system/app/GoogleTTS.apk
rm -rf /system/app/GoogleTTS.odex
rm -rf /system/app/GoogleVrCore
rm -rf /system/app/GoogleVrCore.apk
rm -rf /system/app/GoogleVrCore.odex
rm -rf /system/app/GoogleZhuyinIME
rm -rf /system/app/GoogleZhuyinIME.apk
rm -rf /system/app/GoogleZhuyinIME.odex
rm -rf /system/app/Hangouts
rm -rf /system/app/Hangouts.apk
rm -rf /system/app/Hangouts.odex
rm -rf /system/app/HangoutsDialer
rm -rf /system/app/HangoutsDialer.apk
rm -rf /system/app/HangoutsDialer.odex
rm -rf /system/app/HelpRtcPrebuilt
rm -rf /system/app/HelpRtcPrebuilt.apk
rm -rf /system/app/HelpRtcPrebuilt.odex
rm -rf /system/app/HotwordEnrollment
rm -rf /system/app/HotwordEnrollment.apk
rm -rf /system/app/HotwordEnrollment.odex
rm -rf /system/app/HotwordEnrollmentOKGoogleWCD9340
rm -rf /system/app/HotwordEnrollmentOKGoogleWCD9340.apk
rm -rf /system/app/HotwordEnrollmentOKGoogleWCD9340.odex
rm -rf /system/app/HotwordEnrollmentXGoogleWCD9340
rm -rf /system/app/HotwordEnrollmentXGoogleWCD9340.apk
rm -rf /system/app/HotwordEnrollmentXGoogleWCD9340.odex
rm -rf /system/app/iWnnIME
rm -rf /system/app/iWnnIME.apk
rm -rf /system/app/iWnnIME.odex
rm -rf /system/app/iWnnIME_Kbd_White
rm -rf /system/app/iWnnIME_Kbd_White.apk
rm -rf /system/app/iWnnIME_Kbd_White.odex
rm -rf /system/app/Keep
rm -rf /system/app/Keep.apk
rm -rf /system/app/Keep.odex
rm -rf /system/app/KoreanIME
rm -rf /system/app/KoreanIME.apk
rm -rf /system/app/KoreanIME.odex
rm -rf /system/app/LatinIME
rm -rf /system/app/LatinIME.apk
rm -rf /system/app/LatinIME.odex
rm -rf /system/app/LatinImeDictionaryPack
rm -rf /system/app/LatinImeDictionaryPack.apk
rm -rf /system/app/LatinImeDictionaryPack.odex
rm -rf /system/app/LatinImeGoogle
rm -rf /system/app/LatinImeGoogle.apk
rm -rf /system/app/LatinImeGoogle.odex
rm -rf /system/app/LatinIMEGooglePrebuilt
rm -rf /system/app/LatinIMEGooglePrebuilt.apk
rm -rf /system/app/LatinIMEGooglePrebuilt.odex
rm -rf /system/app/LatinImeTutorial
rm -rf /system/app/LatinImeTutorial.apk
rm -rf /system/app/LatinImeTutorial.odex
rm -rf /system/app/Magazines
rm -rf /system/app/Magazines.apk
rm -rf /system/app/Magazines.odex
rm -rf /system/app/Maps
rm -rf /system/app/Maps.apk
rm -rf /system/app/Maps.odex
rm -rf /system/app/MarketUpdater
rm -rf /system/app/MarketUpdater.apk
rm -rf /system/app/MarketUpdater.odex
rm -rf /system/app/MediaUploader
rm -rf /system/app/MediaUploader.apk
rm -rf /system/app/MediaUploader.odex
rm -rf /system/app/Music2
rm -rf /system/app/Music2.apk
rm -rf /system/app/Music2.odex
rm -rf /system/app/NetworkLocation
rm -rf /system/app/NetworkLocation.apk
rm -rf /system/app/NetworkLocation.odex
rm -rf /system/app/Newsstand
rm -rf /system/app/Newsstand.apk
rm -rf /system/app/Newsstand.odex
rm -rf /system/app/NewsstandStub
rm -rf /system/app/NewsstandStub.apk
rm -rf /system/app/NewsstandStub.odex
rm -rf /system/app/NewsWeather
rm -rf /system/app/NewsWeather.apk
rm -rf /system/app/NewsWeather.odex
rm -rf /system/app/NexusLauncherIcons
rm -rf /system/app/NexusLauncherIcons.apk
rm -rf /system/app/NexusLauncherIcons.odex
rm -rf /system/app/NexusLauncherPrebuilt
rm -rf /system/app/NexusLauncherPrebuilt.apk
rm -rf /system/app/NexusLauncherPrebuilt.odex
rm -rf /system/app/NexusWallpapersStubPrebuilt2017
rm -rf /system/app/NexusWallpapersStubPrebuilt2017.apk
rm -rf /system/app/NexusWallpapersStubPrebuilt2017.odex
rm -rf /system/app/OccamQuickOffice
rm -rf /system/app/OccamQuickOffice.apk
rm -rf /system/app/OccamQuickOffice.odex
rm -rf /system/app/OneTimeInitializer
rm -rf /system/app/OneTimeInitializer.apk
rm -rf /system/app/OneTimeInitializer.odex
rm -rf /system/app/PartnerBookmarksProvider
rm -rf /system/app/PartnerBookmarksProvider.apk
rm -rf /system/app/PartnerBookmarksProvider.odex
rm -rf /system/app/Phonesky
rm -rf /system/app/Phonesky.apk
rm -rf /system/app/Phonesky.odex
rm -rf /system/app/Photos
rm -rf /system/app/Photos.apk
rm -rf /system/app/Photos.odex
rm -rf /system/app/PlayAutoInstallConfig
rm -rf /system/app/PlayAutoInstallConfig.apk
rm -rf /system/app/PlayAutoInstallConfig.odex
rm -rf /system/app/PlayGames
rm -rf /system/app/PlayGames.apk
rm -rf /system/app/PlayGames.odex
rm -rf /system/app/PlayStore
rm -rf /system/app/PlayStore.apk
rm -rf /system/app/PlayStore.odex
rm -rf /system/app/PlusOne
rm -rf /system/app/PlusOne.apk
rm -rf /system/app/PlusOne.odex
rm -rf /system/app/PrebuiltBugle
rm -rf /system/app/PrebuiltBugle.apk
rm -rf /system/app/PrebuiltBugle.odex
rm -rf /system/app/PrebuiltBugleStub
rm -rf /system/app/PrebuiltBugleStub.apk
rm -rf /system/app/PrebuiltBugleStub.odex
rm -rf /system/app/PrebuiltDeskClockGoogle
rm -rf /system/app/PrebuiltDeskClockGoogle.apk
rm -rf /system/app/PrebuiltDeskClockGoogle.odex
rm -rf /system/app/PrebuiltEmailGoogle
rm -rf /system/app/PrebuiltEmailGoogle.apk
rm -rf /system/app/PrebuiltEmailGoogle.odex
rm -rf /system/app/PrebuiltExchange3Google
rm -rf /system/app/PrebuiltExchange3Google.apk
rm -rf /system/app/PrebuiltExchange3Google.odex
rm -rf /system/app/PrebuiltGmail
rm -rf /system/app/PrebuiltGmail.apk
rm -rf /system/app/PrebuiltGmail.odex
rm -rf /system/app/PrebuiltGmsCore
rm -rf /system/app/PrebuiltGmsCore.apk
rm -rf /system/app/PrebuiltGmsCore.odex
rm -rf /system/app/PrebuiltGmsCorePix
rm -rf /system/app/PrebuiltGmsCorePix.apk
rm -rf /system/app/PrebuiltGmsCorePix.odex
rm -rf /system/app/PrebuiltKeep
rm -rf /system/app/PrebuiltKeep.apk
rm -rf /system/app/PrebuiltKeep.odex
rm -rf /system/app/PrebuiltKeepStub
rm -rf /system/app/PrebuiltKeepStub.apk
rm -rf /system/app/PrebuiltKeepStub.odex
rm -rf /system/app/PrebuiltNewsWeather
rm -rf /system/app/PrebuiltNewsWeather.apk
rm -rf /system/app/PrebuiltNewsWeather.odex
rm -rf /system/app/PrintSpooler
rm -rf /system/app/PrintSpooler.apk
rm -rf /system/app/PrintSpooler.odex
rm -rf /system/app/QuickOffice
rm -rf /system/app/QuickOffice.apk
rm -rf /system/app/QuickOffice.odex
rm -rf /system/app/QuickSearchBox
rm -rf /system/app/QuickSearchBox.apk
rm -rf /system/app/QuickSearchBox.odex
rm -rf /system/app/SettingsGoogle
rm -rf /system/app/SettingsGoogle.apk
rm -rf /system/app/SettingsGoogle.odex
rm -rf /system/app/SetupWizard
rm -rf /system/app/SetupWizard.apk
rm -rf /system/app/SetupWizard.odex
rm -rf /system/app/StorageManagerGoogle
rm -rf /system/app/StorageManagerGoogle.apk
rm -rf /system/app/StorageManagerGoogle.odex
rm -rf /system/app/Street
rm -rf /system/app/Street.apk
rm -rf /system/app/Street.odex
rm -rf /system/app/SystemUIGoogle
rm -rf /system/app/SystemUIGoogle.apk
rm -rf /system/app/SystemUIGoogle.odex
rm -rf /system/app/Tag.apk
rm -rf /system/app/TagGoogle
rm -rf /system/app/TagGoogle.apk
rm -rf /system/app/TagGoogle.odex
rm -rf /system/app/Talk
rm -rf /system/app/Talk.apk
rm -rf /system/app/Talk.odex
rm -rf /system/app/talkback
rm -rf /system/app/talkback.apk
rm -rf /system/app/talkback.odex
rm -rf /system/app/TranslatePrebuilt
rm -rf /system/app/TranslatePrebuilt.apk
rm -rf /system/app/TranslatePrebuilt.odex
rm -rf /system/app/Turbo
rm -rf /system/app/Turbo.apk
rm -rf /system/app/Turbo.odex
rm -rf /system/app/Tycho
rm -rf /system/app/Tycho.apk
rm -rf /system/app/Tycho.odex
rm -rf /system/app/Velvet
rm -rf /system/app/Velvet.apk
rm -rf /system/app/Velvet.odex
rm -rf /system/app/Velvet_update
rm -rf /system/app/Velvet_update.apk
rm -rf /system/app/Velvet_update.odex
rm -rf /system/app/Vending
rm -rf /system/app/Vending.apk
rm -rf /system/app/Vending.odex
rm -rf /system/app/Videos
rm -rf /system/app/Videos.apk
rm -rf /system/app/Videos.odex
rm -rf /system/app/VoiceSearch
rm -rf /system/app/VoiceSearch.apk
rm -rf /system/app/VoiceSearch.odex
rm -rf /system/app/VoiceSearchStub
rm -rf /system/app/VoiceSearchStub.apk
rm -rf /system/app/VoiceSearchStub.odex
rm -rf /system/app/Wallet
rm -rf /system/app/Wallet.apk
rm -rf /system/app/Wallet.odex
rm -rf /system/app/WallpaperPickerGooglePrebuilt
rm -rf /system/app/WallpaperPickerGooglePrebuilt.apk
rm -rf /system/app/WallpaperPickerGooglePrebuilt.odex
rm -rf /system/app/WallpapersBReel2017
rm -rf /system/app/WallpapersBReel2017.apk
rm -rf /system/app/WallpapersBReel2017.odex
rm -rf /system/app/WebViewGoogle
rm -rf /system/app/WebViewGoogle.apk
rm -rf /system/app/WebViewGoogle.odex
rm -rf /system/app/WebViewStub
rm -rf /system/app/WebViewStub.apk
rm -rf /system/app/WebViewStub.odex
rm -rf /system/app/YouTube
rm -rf /system/app/YouTube.apk
rm -rf /system/app/YouTube.odex
rm -rf /system/bin/wmdsi
rm -rf /system/etc/ambient/matcher.leveldb
rm -rf /system/etc/default-permissions/default-permissions.xml
rm -rf /system/etc/default-permissions/opengapps-permissions.xml
rm -rf /system/etc/firmware/dnd.descriptor
rm -rf /system/etc/firmware/dnd.sound_model
rm -rf /system/etc/firmware/music_detector.descriptor
rm -rf /system/etc/firmware/music_detector.sound_model
rm -rf /system/etc/g.prop
rm -rf /system/etc/permissions/com.google.android.camera.experimental2015.xml
rm -rf /system/etc/permissions/com.google.android.camera.experimental2016.xml
rm -rf /system/etc/permissions/com.google.android.camera.experimental2017.xml
rm -rf /system/etc/permissions/com.google.android.camera.experimental2018.xml
rm -rf /system/etc/permissions/com.google.android.camera2.xml
rm -rf /system/etc/permissions/com.google.android.dialer.support.xml
rm -rf /system/etc/permissions/com.google.android.maps.xml
rm -rf /system/etc/permissions/com.google.android.media.effects.xml
rm -rf /system/etc/permissions/com.google.android.pano.v1.xml
rm -rf /system/etc/permissions/com.google.vr.platform.xml
rm -rf /system/etc/permissions/com.google.widevine.software.drm.xml
rm -rf /system/etc/permissions/features.xml
rm -rf /system/etc/preferred-apps/google.xml
rm -rf /system/etc/sysconfig/dialer_experience.xml
rm -rf /system/etc/sysconfig/framework-sysconfig.xml
rm -rf /system/etc/sysconfig/google.xml
rm -rf /system/etc/sysconfig/google_build.xml
rm -rf /system/etc/sysconfig/google_vr_build.xml
rm -rf /system/etc/sysconfig/pixel_2017.xml
rm -rf /system/etc/sysconfig/pixel_2018.xml
rm -rf /system/etc/sysconfig/whitelist_com.android.omadm.service.xml
rm -rf /system/etc/updatecmds/google_generic_update.txt
rm -rf /system/framework/com.google.android.camera.experimental2015.jar
rm -rf /system/framework/com.google.android.camera.experimental2016.jar
rm -rf /system/framework/com.google.android.camera2.jar
rm -rf /system/framework/com.google.android.dialer.support.jar
rm -rf /system/framework/com.google.android.maps.jar
rm -rf /system/framework/com.google.android.media.effects.jar
rm -rf /system/framework/com.google.android.pano.v1.jar
rm -rf /system/framework/com.google.widevine.software.drm.jar
rm -rf /system/lib/lib_dic_*
rm -rf /system/lib/libAppDataSearch.so
rm -rf /system/lib/libbitmap_parcel.so
rm -rf /system/lib/libchrome*
rm -rf /system/lib/libchromeview.so
rm -rf /system/lib/libconscrypt_gmscore_jni.so
rm -rf /system/lib/libcrashreporter.so
rm -rf /system/lib/libdocscanner*
rm -rf /system/lib/libdocsimageutils.so
rm -rf /system/lib/libearthandroid.so
rm -rf /system/lib/libearthmobile.so
rm -rf /system/lib/libEnjemailuri.so
rm -rf /system/lib/libennjcon.so
rm -rf /system/lib/libennjubase*
rm -rf /system/lib/libennjyomi.so
rm -rf /system/lib/libfacelock_jni.so
rm -rf /system/lib/libfacenet.so
rm -rf /system/lib/libfacetracker.so
rm -rf /system/lib/libfilterframework_jni.so
rm -rf /system/lib/libfilterpack_facedetect.so
rm -rf /system/lib/libflint_engine_jni_api.so
rm -rf /system/lib/libfoxit.so
rm -rf /system/lib/libframesequence.so
rm -rf /system/lib/libfrsdk.so
rm -rf /system/lib/libgames_rtmp_jni.so
rm -rf /system/lib/libgcam.so
rm -rf /system/lib/libgcam_swig_jni.so
rm -rf /system/lib/libgcastv2*
rm -rf /system/lib/libgcomm_jni.so
rm -rf /system/lib/libgmm-jni.so
rm -rf /system/lib/libgms-ocrclient.so
rm -rf /system/lib/libgmscore.so
rm -rf /system/lib/libgoggles_clientvision.so
rm -rf /system/lib/libgoogle_*
rm -rf /system/lib/libgtalk_jni.so
rm -rf /system/lib/libgtalk_stabilize.so
rm -rf /system/lib/libiwnn.so
rm -rf /system/lib/libjgcastservice.so
rm -rf /system/lib/libjni_eglfence.so
rm -rf /system/lib/libjni_filtershow_filters.so
rm -rf /system/lib/libjni_googlepinyinime_*
rm -rf /system/lib/libjni_koreanime.so
rm -rf /system/lib/libjni_latinime.so
rm -rf /system/lib/libjni_latinimegoogle.so
rm -rf /system/lib/libjni_t13n_shared_engine.so
rm -rf /system/lib/libjni_tinyplanet.so
rm -rf /system/lib/libjni_unbundled_latinimegoogle.so
rm -rf /system/lib/liblightcycle.so
rm -rf /system/lib/liblinearalloc.so
rm -rf /system/lib/libm2ts_player.so
rm -rf /system/lib/libmicro_hotword_jni.so
rm -rf /system/lib/libmoviemaker-jni.so
rm -rf /system/lib/libnativehelper_compat.so
rm -rf /system/lib/libnativehelper_compat_libc++.so
rm -rf /system/lib/libndk1.so
rm -rf /system/lib/libnetjni.so
rm -rf /system/lib/libnjaddress.so
rm -rf /system/lib/libnjcon.so
rm -rf /system/lib/libnjemoji.so
rm -rf /system/lib/libnjexyomi.so
rm -rf /system/lib/libnjfzk.so
rm -rf /system/lib/libnjkaomoji.so
rm -rf /system/lib/libnjname.so
rm -rf /system/lib/libnjtan.so
rm -rf /system/lib/libnjubase*
rm -rf /system/lib/libnjubaseidx1.so
rm -rf /system/lib/libnjubaseidx2.so
rm -rf /system/lib/libocrclient.so
rm -rf /system/lib/libpatts_engine_*
rm -rf /system/lib/libphotoeditor_native.so
rm -rf /system/lib/libpicowrapper.so
rm -rf /system/lib/libplus_jni_v8.so
rm -rf /system/lib/librectifier*
rm -rf /system/lib/librefocus.so
rm -rf /system/lib/librs.antblur.so
rm -rf /system/lib/librs.antblur_*
rm -rf /system/lib/librs.drama.so
rm -rf /system/lib/librs.film_base.so
rm -rf /system/lib/librs.fixedframe.so
rm -rf /system/lib/librs.grey.so
rm -rf /system/lib/librs.image_wrapper.so
rm -rf /system/lib/librs.layered_filter_f32.so
rm -rf /system/lib/librs.retrolux.so
rm -rf /system/lib/librsjni.so
rm -rf /system/lib/libRSSupport.so
rm -rf /system/lib/libsense.so
rm -rf /system/lib/libspeexwrapper.so
rm -rf /system/lib/libspeexwrapper_ub*
rm -rf /system/lib/libsslwrapper_jni.so
rm -rf /system/lib/libstlport_shared.so
rm -rf /system/lib/libvcdecoder_jni.so
rm -rf /system/lib/libvideochat_jni.so
rm -rf /system/lib/libvideochat_stabilize.so
rm -rf /system/lib/libvoicesearch.so
rm -rf /system/lib/libvorbisencoder.so
rm -rf /system/lib/libwallpapers-breel-jni.so
rm -rf /system/lib/libwebp_android.so
rm -rf /system/lib/libwebrtc_audio_coding.so
rm -rf /system/lib/libWhisper.so
rm -rf /system/lib/libWVphoneAPI.so
rm -rf /system/lib/modules/modules.dep.bb
rm -rf /system/lib64/lib_dic_*
rm -rf /system/lib64/libAppDataSearch.so
rm -rf /system/lib64/libbitmap_parcel.so
rm -rf /system/lib64/libchrome*
rm -rf /system/lib64/libchromeview.so
rm -rf /system/lib64/libconscrypt_gmscore_jni.so
rm -rf /system/lib64/libcrashreporter.so
rm -rf /system/lib64/libdocscanner*
rm -rf /system/lib64/libdocsimageutils.so
rm -rf /system/lib64/libearthandroid.so
rm -rf /system/lib64/libearthmobile.so
rm -rf /system/lib64/libEnjemailuri.so
rm -rf /system/lib64/libennjcon.so
rm -rf /system/lib64/libennjubase*
rm -rf /system/lib64/libennjyomi.so
rm -rf /system/lib64/libfacelock_jni.so
rm -rf /system/lib64/libfacenet.so
rm -rf /system/lib64/libfacetracker.so
rm -rf /system/lib64/libfilterframework_jni.so
rm -rf /system/lib64/libfilterpack_facedetect.so
rm -rf /system/lib64/libflint_engine_jni_api.so
rm -rf /system/lib64/libfoxit.so
rm -rf /system/lib64/libframesequence.so
rm -rf /system/lib64/libfrsdk.so
rm -rf /system/lib64/libgames_rtmp_jni.so
rm -rf /system/lib64/libgcam.so
rm -rf /system/lib64/libgcam_swig_jni.so
rm -rf /system/lib64/libgcastv2*
rm -rf /system/lib64/libgcomm_jni.so
rm -rf /system/lib64/libgmm-jni.so
rm -rf /system/lib64/libgms-ocrclient.so
rm -rf /system/lib64/libgmscore.so
rm -rf /system/lib64/libgoggles_clientvision.so
rm -rf /system/lib64/libgoogle_*
rm -rf /system/lib64/libgtalk_jni.so
rm -rf /system/lib64/libgtalk_stabilize.so
rm -rf /system/lib64/libiwnn.so
rm -rf /system/lib64/libjgcastservice.so
rm -rf /system/lib64/libjni_eglfence.so
rm -rf /system/lib64/libjni_filtershow_filters.so
rm -rf /system/lib64/libjni_googlepinyinime_*
rm -rf /system/lib64/libjni_koreanime.so
rm -rf /system/lib64/libjni_latinime.so
rm -rf /system/lib64/libjni_latinimegoogle.so
rm -rf /system/lib64/libjni_t13n_shared_engine.so
rm -rf /system/lib64/libjni_tinyplanet.so
rm -rf /system/lib64/libjni_unbundled_latinimegoogle.so
rm -rf /system/lib64/liblightcycle.so
rm -rf /system/lib64/liblinearalloc.so
rm -rf /system/lib64/libm2ts_player.so
rm -rf /system/lib64/libmicro_hotword_jni.so
rm -rf /system/lib64/libmoviemaker-jni.so
rm -rf /system/lib64/libnativehelper_compat.so
rm -rf /system/lib64/libnativehelper_compat_libc++.so
rm -rf /system/lib64/libndk1.so
rm -rf /system/lib64/libnetjni.so
rm -rf /system/lib64/libnjaddress.so
rm -rf /system/lib64/libnjcon.so
rm -rf /system/lib64/libnjemoji.so
rm -rf /system/lib64/libnjexyomi.so
rm -rf /system/lib64/libnjfzk.so
rm -rf /system/lib64/libnjkaomoji.so
rm -rf /system/lib64/libnjname.so
rm -rf /system/lib64/libnjtan.so
rm -rf /system/lib64/libnjubase*
rm -rf /system/lib64/libnjubaseidx1.so
rm -rf /system/lib64/libnjubaseidx2.so
rm -rf /system/lib64/libocrclient.so
rm -rf /system/lib64/libpatts_engine_*
rm -rf /system/lib64/libphotoeditor_native.so
rm -rf /system/lib64/libpicowrapper.so
rm -rf /system/lib64/libplus_jni_v8.so
rm -rf /system/lib64/librectifier*
rm -rf /system/lib64/librefocus.so
rm -rf /system/lib64/librs.antblur.so
rm -rf /system/lib64/librs.antblur_*
rm -rf /system/lib64/librs.drama.so
rm -rf /system/lib64/librs.film_base.so
rm -rf /system/lib64/librs.fixedframe.so
rm -rf /system/lib64/librs.grey.so
rm -rf /system/lib64/librs.image_wrapper.so
rm -rf /system/lib64/librs.layered_filter_f32.so
rm -rf /system/lib64/librs.retrolux.so
rm -rf /system/lib64/librsjni.so
rm -rf /system/lib64/libRSSupport.so
rm -rf /system/lib64/libsense.so
rm -rf /system/lib64/libspeexwrapper.so
rm -rf /system/lib64/libspeexwrapper_ub*
rm -rf /system/lib64/libsslwrapper_jni.so
rm -rf /system/lib64/libstlport_shared.so
rm -rf /system/lib64/libvcdecoder_jni.so
rm -rf /system/lib64/libvideochat_jni.so
rm -rf /system/lib64/libvideochat_stabilize.so
rm -rf /system/lib64/libvoicesearch.so
rm -rf /system/lib64/libvorbisencoder.so
rm -rf /system/lib64/libwallpapers-breel-jni.so
rm -rf /system/lib64/libwebp_android.so
rm -rf /system/lib64/libwebrtc_audio_coding.so
rm -rf /system/lib64/libWhisper.so
rm -rf /system/lib64/libWVphoneAPI.so
rm -rf /system/lib64/modules/modules.dep.bb
rm -rf /system/priv-app/AmbientSensePrebuilt
rm -rf /system/priv-app/AmbientSensePrebuilt.apk
rm -rf /system/priv-app/AmbientSensePrebuilt.odex
rm -rf /system/priv-app/AndroidForWork
rm -rf /system/priv-app/AndroidForWork.apk
rm -rf /system/priv-app/AndroidForWork.odex
rm -rf /system/priv-app/AndroidMigratePrebuilt
rm -rf /system/priv-app/AndroidMigratePrebuilt.apk
rm -rf /system/priv-app/AndroidMigratePrebuilt.odex
rm -rf /system/priv-app/AndroidPlatformServices
rm -rf /system/priv-app/AndroidPlatformServices.apk
rm -rf /system/priv-app/AndroidPlatformServices.odex
rm -rf /system/priv-app/BackupRestoreConfirmation
rm -rf /system/priv-app/BackupRestoreConfirmation.apk
rm -rf /system/priv-app/BackupRestoreConfirmation.odex
rm -rf /system/priv-app/Books
rm -rf /system/priv-app/Books.apk
rm -rf /system/priv-app/Books.odex
rm -rf /system/priv-app/BooksPhone
rm -rf /system/priv-app/BooksPhone.apk
rm -rf /system/priv-app/BooksPhone.odex
rm -rf /system/priv-app/BooksStub
rm -rf /system/priv-app/BooksStub.apk
rm -rf /system/priv-app/BooksStub.odex
rm -rf /system/priv-app/BrowserProviderProxy
rm -rf /system/priv-app/BrowserProviderProxy.apk
rm -rf /system/priv-app/BrowserProviderProxy.odex
rm -rf /system/priv-app/CalculatorGoogle
rm -rf /system/priv-app/CalculatorGoogle.apk
rm -rf /system/priv-app/CalculatorGoogle.odex
rm -rf /system/priv-app/CalculatorGooglePrebuilt
rm -rf /system/priv-app/CalculatorGooglePrebuilt.apk
rm -rf /system/priv-app/CalculatorGooglePrebuilt.odex
rm -rf /system/priv-app/Calendar
rm -rf /system/priv-app/Calendar.apk
rm -rf /system/priv-app/Calendar.odex
rm -rf /system/priv-app/CalendarGoogle
rm -rf /system/priv-app/CalendarGoogle.apk
rm -rf /system/priv-app/CalendarGoogle.odex
rm -rf /system/priv-app/CalendarGooglePrebuilt
rm -rf /system/priv-app/CalendarGooglePrebuilt.apk
rm -rf /system/priv-app/CalendarGooglePrebuilt.odex
rm -rf /system/priv-app/CalendarProvider
rm -rf /system/priv-app/CalendarProvider.apk
rm -rf /system/priv-app/CalendarProvider.odex
rm -rf /system/priv-app/CarHomeGoogle
rm -rf /system/priv-app/CarHomeGoogle.apk
rm -rf /system/priv-app/CarHomeGoogle.odex
rm -rf /system/priv-app/CellBroadcastReceiver
rm -rf /system/priv-app/CellBroadcastReceiver.apk
rm -rf /system/priv-app/CellBroadcastReceiver.odex
rm -rf /system/priv-app/Chrome
rm -rf /system/priv-app/Chrome.apk
rm -rf /system/priv-app/Chrome.odex
rm -rf /system/priv-app/ChromeBookmarksSyncAdapter
rm -rf /system/priv-app/ChromeBookmarksSyncAdapter.apk
rm -rf /system/priv-app/ChromeBookmarksSyncAdapter.odex
rm -rf /system/priv-app/CloudPrint
rm -rf /system/priv-app/CloudPrint.apk
rm -rf /system/priv-app/CloudPrint.odex
rm -rf /system/priv-app/CloudPrint2
rm -rf /system/priv-app/CloudPrint2.apk
rm -rf /system/priv-app/CloudPrint2.odex
rm -rf /system/priv-app/ConfigUpdater
rm -rf /system/priv-app/ConfigUpdater.apk
rm -rf /system/priv-app/ConfigUpdater.odex
rm -rf /system/priv-app/ConnMO
rm -rf /system/priv-app/ConnMO.apk
rm -rf /system/priv-app/ConnMO.odex
rm -rf /system/priv-app/Currents
rm -rf /system/priv-app/Currents.apk
rm -rf /system/priv-app/Currents.odex
rm -rf /system/priv-app/DeskClockGoogle
rm -rf /system/priv-app/DeskClockGoogle.apk
rm -rf /system/priv-app/DeskClockGoogle.odex
rm -rf /system/priv-app/DMAgent
rm -rf /system/priv-app/DMAgent.apk
rm -rf /system/priv-app/DMAgent.odex
rm -rf /system/priv-app/Drive
rm -rf /system/priv-app/Drive.apk
rm -rf /system/priv-app/Drive.odex
rm -rf /system/priv-app/Duo
rm -rf /system/priv-app/Duo.apk
rm -rf /system/priv-app/Duo.odex
rm -rf /system/priv-app/EditorsDocs
rm -rf /system/priv-app/EditorsDocs.apk
rm -rf /system/priv-app/EditorsDocs.odex
rm -rf /system/priv-app/EditorsDocsStub
rm -rf /system/priv-app/EditorsDocsStub.apk
rm -rf /system/priv-app/EditorsDocsStub.odex
rm -rf /system/priv-app/EditorsSheets
rm -rf /system/priv-app/EditorsSheets.apk
rm -rf /system/priv-app/EditorsSheets.odex
rm -rf /system/priv-app/EditorsSheetsStub
rm -rf /system/priv-app/EditorsSheetsStub.apk
rm -rf /system/priv-app/EditorsSheetsStub.odex
rm -rf /system/priv-app/EditorsSlides
rm -rf /system/priv-app/EditorsSlides.apk
rm -rf /system/priv-app/EditorsSlides.odex
rm -rf /system/priv-app/EditorsSlidesStub
rm -rf /system/priv-app/EditorsSlidesStub.apk
rm -rf /system/priv-app/EditorsSlidesStub.odex
rm -rf /system/priv-app/EuiccGoogle
rm -rf /system/priv-app/EuiccGoogle.apk
rm -rf /system/priv-app/EuiccGoogle.odex
rm -rf /system/priv-app/ExchangeServices
rm -rf /system/priv-app/ExchangeServices.apk
rm -rf /system/priv-app/ExchangeServices.odex
rm -rf /system/priv-app/FaceLock
rm -rf /system/priv-app/FaceLock.apk
rm -rf /system/priv-app/FaceLock.odex
rm -rf /system/priv-app/Finsky
rm -rf /system/priv-app/Finsky.apk
rm -rf /system/priv-app/Finsky.odex
rm -rf /system/priv-app/FitnessPrebuilt
rm -rf /system/priv-app/FitnessPrebuilt.apk
rm -rf /system/priv-app/FitnessPrebuilt.odex
rm -rf /system/priv-app/FOTAKill
rm -rf /system/priv-app/FOTAKill.apk
rm -rf /system/priv-app/FOTAKill.odex
rm -rf /system/priv-app/GalleryGoogle
rm -rf /system/priv-app/GalleryGoogle.apk
rm -rf /system/priv-app/GalleryGoogle.odex
rm -rf /system/priv-app/GCS
rm -rf /system/priv-app/GCS.apk
rm -rf /system/priv-app/GCS.odex
rm -rf /system/priv-app/GenieWidget
rm -rf /system/priv-app/GenieWidget.apk
rm -rf /system/priv-app/GenieWidget.odex
rm -rf /system/priv-app/Gmail
rm -rf /system/priv-app/Gmail.apk
rm -rf /system/priv-app/Gmail.odex
rm -rf /system/priv-app/Gmail2
rm -rf /system/priv-app/Gmail2.apk
rm -rf /system/priv-app/Gmail2.odex
rm -rf /system/priv-app/GmsCore
rm -rf /system/priv-app/GmsCore.apk
rm -rf /system/priv-app/GmsCore.odex
rm -rf /system/priv-app/GmsCore_update
rm -rf /system/priv-app/GmsCore_update.apk
rm -rf /system/priv-app/GmsCore_update.odex
rm -rf /system/priv-app/GmsCoreSetupPrebuilt
rm -rf /system/priv-app/GmsCoreSetupPrebuilt.apk
rm -rf /system/priv-app/GmsCoreSetupPrebuilt.odex
rm -rf /system/priv-app/GoogleBackupTransport
rm -rf /system/priv-app/GoogleBackupTransport.apk
rm -rf /system/priv-app/GoogleBackupTransport.odex
rm -rf /system/priv-app/GoogleCalendar
rm -rf /system/priv-app/GoogleCalendar.apk
rm -rf /system/priv-app/GoogleCalendar.odex
rm -rf /system/priv-app/GoogleCalendarSyncAdapter
rm -rf /system/priv-app/GoogleCalendarSyncAdapter.apk
rm -rf /system/priv-app/GoogleCalendarSyncAdapter.odex
rm -rf /system/priv-app/GoogleCamera
rm -rf /system/priv-app/GoogleCamera.apk
rm -rf /system/priv-app/GoogleCamera.odex
rm -rf /system/priv-app/GoogleCameraLegacy
rm -rf /system/priv-app/GoogleCameraLegacy.apk
rm -rf /system/priv-app/GoogleCameraLegacy.odex
rm -rf /system/priv-app/GoogleCloudPrint
rm -rf /system/priv-app/GoogleCloudPrint.apk
rm -rf /system/priv-app/GoogleCloudPrint.odex
rm -rf /system/priv-app/GoogleContacts
rm -rf /system/priv-app/GoogleContacts.apk
rm -rf /system/priv-app/GoogleContacts.odex
rm -rf /system/priv-app/GoogleContactsSyncAdapter
rm -rf /system/priv-app/GoogleContactsSyncAdapter.apk
rm -rf /system/priv-app/GoogleContactsSyncAdapter.odex
rm -rf /system/priv-app/GoogleDialer
rm -rf /system/priv-app/GoogleDialer.apk
rm -rf /system/priv-app/GoogleDialer.odex
rm -rf /system/priv-app/GoogleEars
rm -rf /system/priv-app/GoogleEars.apk
rm -rf /system/priv-app/GoogleEars.odex
rm -rf /system/priv-app/GoogleEarth
rm -rf /system/priv-app/GoogleEarth.apk
rm -rf /system/priv-app/GoogleEarth.odex
rm -rf /system/priv-app/GoogleExtServices
rm -rf /system/priv-app/GoogleExtServices.apk
rm -rf /system/priv-app/GoogleExtServices.odex
rm -rf /system/priv-app/GoogleExtShared
rm -rf /system/priv-app/GoogleExtShared.apk
rm -rf /system/priv-app/GoogleExtShared.odex
rm -rf /system/priv-app/GoogleFeedback
rm -rf /system/priv-app/GoogleFeedback.apk
rm -rf /system/priv-app/GoogleFeedback.odex
rm -rf /system/priv-app/GoogleHangouts
rm -rf /system/priv-app/GoogleHangouts.apk
rm -rf /system/priv-app/GoogleHangouts.odex
rm -rf /system/priv-app/GoogleHindiIME
rm -rf /system/priv-app/GoogleHindiIME.apk
rm -rf /system/priv-app/GoogleHindiIME.odex
rm -rf /system/priv-app/GoogleHome
rm -rf /system/priv-app/GoogleHome.apk
rm -rf /system/priv-app/GoogleHome.odex
rm -rf /system/priv-app/GoogleJapaneseInput
rm -rf /system/priv-app/GoogleJapaneseInput.apk
rm -rf /system/priv-app/GoogleJapaneseInput.odex
rm -rf /system/priv-app/GoogleKeep
rm -rf /system/priv-app/GoogleKeep.apk
rm -rf /system/priv-app/GoogleKeep.odex
rm -rf /system/priv-app/GoogleLatinIme
rm -rf /system/priv-app/GoogleLatinIme.apk
rm -rf /system/priv-app/GoogleLatinIme.odex
rm -rf /system/priv-app/GoogleLoginService
rm -rf /system/priv-app/GoogleLoginService.apk
rm -rf /system/priv-app/GoogleLoginService.odex
rm -rf /system/priv-app/GoogleMusic
rm -rf /system/priv-app/GoogleMusic.apk
rm -rf /system/priv-app/GoogleMusic.odex
rm -rf /system/priv-app/GoogleNow
rm -rf /system/priv-app/GoogleNow.apk
rm -rf /system/priv-app/GoogleNow.odex
rm -rf /system/priv-app/GoogleNowVoiceSearch
rm -rf /system/priv-app/GoogleNowVoiceSearch.apk
rm -rf /system/priv-app/GoogleNowVoiceSearch.odex
rm -rf /system/priv-app/GoogleOneTimeInitializer
rm -rf /system/priv-app/GoogleOneTimeInitializer.apk
rm -rf /system/priv-app/GoogleOneTimeInitializer.odex
rm -rf /system/priv-app/GooglePartnerSetup
rm -rf /system/priv-app/GooglePartnerSetup.apk
rm -rf /system/priv-app/GooglePartnerSetup.odex
rm -rf /system/priv-app/GooglePinyinIME
rm -rf /system/priv-app/GooglePinyinIME.apk
rm -rf /system/priv-app/GooglePinyinIME.odex
rm -rf /system/priv-app/GooglePlay
rm -rf /system/priv-app/GooglePlay.apk
rm -rf /system/priv-app/GooglePlay.odex
rm -rf /system/priv-app/GooglePlus
rm -rf /system/priv-app/GooglePlus.apk
rm -rf /system/priv-app/GooglePlus.odex
rm -rf /system/priv-app/GooglePrintRecommendationService
rm -rf /system/priv-app/GooglePrintRecommendationService.apk
rm -rf /system/priv-app/GooglePrintRecommendationService.odex
rm -rf /system/priv-app/GoogleQuickSearchBox
rm -rf /system/priv-app/GoogleQuickSearchBox.apk
rm -rf /system/priv-app/GoogleQuickSearchBox.odex
rm -rf /system/priv-app/GoogleSearch
rm -rf /system/priv-app/GoogleSearch.apk
rm -rf /system/priv-app/GoogleSearch.odex
rm -rf /system/priv-app/GoogleServicesFramework
rm -rf /system/priv-app/GoogleServicesFramework.apk
rm -rf /system/priv-app/GoogleServicesFramework.odex
rm -rf /system/priv-app/GoogleTTS
rm -rf /system/priv-app/GoogleTTS.apk
rm -rf /system/priv-app/GoogleTTS.odex
rm -rf /system/priv-app/GoogleVrCore
rm -rf /system/priv-app/GoogleVrCore.apk
rm -rf /system/priv-app/GoogleVrCore.odex
rm -rf /system/priv-app/GoogleZhuyinIME
rm -rf /system/priv-app/GoogleZhuyinIME.apk
rm -rf /system/priv-app/GoogleZhuyinIME.odex
rm -rf /system/priv-app/Hangouts
rm -rf /system/priv-app/Hangouts.apk
rm -rf /system/priv-app/Hangouts.odex
rm -rf /system/priv-app/HangoutsDialer
rm -rf /system/priv-app/HangoutsDialer.apk
rm -rf /system/priv-app/HangoutsDialer.odex
rm -rf /system/priv-app/HelpRtcPrebuilt
rm -rf /system/priv-app/HelpRtcPrebuilt.apk
rm -rf /system/priv-app/HelpRtcPrebuilt.odex
rm -rf /system/priv-app/HotwordEnrollment
rm -rf /system/priv-app/HotwordEnrollment.apk
rm -rf /system/priv-app/HotwordEnrollment.odex
rm -rf /system/priv-app/HotwordEnrollmentOKGoogleWCD9340
rm -rf /system/priv-app/HotwordEnrollmentOKGoogleWCD9340.apk
rm -rf /system/priv-app/HotwordEnrollmentOKGoogleWCD9340.odex
rm -rf /system/priv-app/HotwordEnrollmentXGoogleWCD9340
rm -rf /system/priv-app/HotwordEnrollmentXGoogleWCD9340.apk
rm -rf /system/priv-app/HotwordEnrollmentXGoogleWCD9340.odex
rm -rf /system/priv-app/iWnnIME
rm -rf /system/priv-app/iWnnIME.apk
rm -rf /system/priv-app/iWnnIME.odex
rm -rf /system/priv-app/iWnnIME_Kbd_White
rm -rf /system/priv-app/iWnnIME_Kbd_White.apk
rm -rf /system/priv-app/iWnnIME_Kbd_White.odex
rm -rf /system/priv-app/Keep
rm -rf /system/priv-app/Keep.apk
rm -rf /system/priv-app/Keep.odex
rm -rf /system/priv-app/KoreanIME
rm -rf /system/priv-app/KoreanIME.apk
rm -rf /system/priv-app/KoreanIME.odex
rm -rf /system/priv-app/LatinIME
rm -rf /system/priv-app/LatinIME.apk
rm -rf /system/priv-app/LatinIME.odex
rm -rf /system/priv-app/LatinImeDictionaryPack
rm -rf /system/priv-app/LatinImeDictionaryPack.apk
rm -rf /system/priv-app/LatinImeDictionaryPack.odex
rm -rf /system/priv-app/LatinImeGoogle
rm -rf /system/priv-app/LatinImeGoogle.apk
rm -rf /system/priv-app/LatinImeGoogle.odex
rm -rf /system/priv-app/LatinIMEGooglePrebuilt
rm -rf /system/priv-app/LatinIMEGooglePrebuilt.apk
rm -rf /system/priv-app/LatinIMEGooglePrebuilt.odex
rm -rf /system/priv-app/LatinImeTutorial
rm -rf /system/priv-app/LatinImeTutorial.apk
rm -rf /system/priv-app/LatinImeTutorial.odex
rm -rf /system/priv-app/Magazines
rm -rf /system/priv-app/Magazines.apk
rm -rf /system/priv-app/Magazines.odex
rm -rf /system/priv-app/Maps
rm -rf /system/priv-app/Maps.apk
rm -rf /system/priv-app/Maps.odex
rm -rf /system/priv-app/MarketUpdater
rm -rf /system/priv-app/MarketUpdater.apk
rm -rf /system/priv-app/MarketUpdater.odex
rm -rf /system/priv-app/MediaUploader
rm -rf /system/priv-app/MediaUploader.apk
rm -rf /system/priv-app/MediaUploader.odex
rm -rf /system/priv-app/Music2
rm -rf /system/priv-app/Music2.apk
rm -rf /system/priv-app/Music2.odex
rm -rf /system/priv-app/NetworkLocation
rm -rf /system/priv-app/NetworkLocation.apk
rm -rf /system/priv-app/NetworkLocation.odex
rm -rf /system/priv-app/Newsstand
rm -rf /system/priv-app/Newsstand.apk
rm -rf /system/priv-app/Newsstand.odex
rm -rf /system/priv-app/NewsstandStub
rm -rf /system/priv-app/NewsstandStub.apk
rm -rf /system/priv-app/NewsstandStub.odex
rm -rf /system/priv-app/NewsWeather
rm -rf /system/priv-app/NewsWeather.apk
rm -rf /system/priv-app/NewsWeather.odex
rm -rf /system/priv-app/NexusLauncherIcons
rm -rf /system/priv-app/NexusLauncherIcons.apk
rm -rf /system/priv-app/NexusLauncherIcons.odex
rm -rf /system/priv-app/NexusLauncherPrebuilt
rm -rf /system/priv-app/NexusLauncherPrebuilt.apk
rm -rf /system/priv-app/NexusLauncherPrebuilt.odex
rm -rf /system/priv-app/NexusWallpapersStubPrebuilt2017
rm -rf /system/priv-app/NexusWallpapersStubPrebuilt2017.apk
rm -rf /system/priv-app/NexusWallpapersStubPrebuilt2017.odex
rm -rf /system/priv-app/OccamQuickOffice
rm -rf /system/priv-app/OccamQuickOffice.apk
rm -rf /system/priv-app/OccamQuickOffice.odex
rm -rf /system/priv-app/OneTimeInitializer
rm -rf /system/priv-app/OneTimeInitializer.apk
rm -rf /system/priv-app/OneTimeInitializer.odex
rm -rf /system/priv-app/PartnerBookmarksProvider
rm -rf /system/priv-app/PartnerBookmarksProvider.apk
rm -rf /system/priv-app/PartnerBookmarksProvider.odex
rm -rf /system/priv-app/Phonesky
rm -rf /system/priv-app/Phonesky.apk
rm -rf /system/priv-app/Phonesky.odex
rm -rf /system/priv-app/Photos
rm -rf /system/priv-app/Photos.apk
rm -rf /system/priv-app/Photos.odex
rm -rf /system/priv-app/PlayAutoInstallConfig
rm -rf /system/priv-app/PlayAutoInstallConfig.apk
rm -rf /system/priv-app/PlayAutoInstallConfig.odex
rm -rf /system/priv-app/PlayGames
rm -rf /system/priv-app/PlayGames.apk
rm -rf /system/priv-app/PlayGames.odex
rm -rf /system/priv-app/PlayStore
rm -rf /system/priv-app/PlayStore.apk
rm -rf /system/priv-app/PlayStore.odex
rm -rf /system/priv-app/PlusOne
rm -rf /system/priv-app/PlusOne.apk
rm -rf /system/priv-app/PlusOne.odex
rm -rf /system/priv-app/PrebuiltBugle
rm -rf /system/priv-app/PrebuiltBugle.apk
rm -rf /system/priv-app/PrebuiltBugle.odex
rm -rf /system/priv-app/PrebuiltBugleStub
rm -rf /system/priv-app/PrebuiltBugleStub.apk
rm -rf /system/priv-app/PrebuiltBugleStub.odex
rm -rf /system/priv-app/PrebuiltDeskClockGoogle
rm -rf /system/priv-app/PrebuiltDeskClockGoogle.apk
rm -rf /system/priv-app/PrebuiltDeskClockGoogle.odex
rm -rf /system/priv-app/PrebuiltEmailGoogle
rm -rf /system/priv-app/PrebuiltEmailGoogle.apk
rm -rf /system/priv-app/PrebuiltEmailGoogle.odex
rm -rf /system/priv-app/PrebuiltExchange3Google
rm -rf /system/priv-app/PrebuiltExchange3Google.apk
rm -rf /system/priv-app/PrebuiltExchange3Google.odex
rm -rf /system/priv-app/PrebuiltGmail
rm -rf /system/priv-app/PrebuiltGmail.apk
rm -rf /system/priv-app/PrebuiltGmail.odex
rm -rf /system/priv-app/PrebuiltGmsCore
rm -rf /system/priv-app/PrebuiltGmsCore.apk
rm -rf /system/priv-app/PrebuiltGmsCore.odex
rm -rf /system/priv-app/PrebuiltGmsCorePix
rm -rf /system/priv-app/PrebuiltGmsCorePix.apk
rm -rf /system/priv-app/PrebuiltGmsCorePix.odex
rm -rf /system/priv-app/PrebuiltKeep
rm -rf /system/priv-app/PrebuiltKeep.apk
rm -rf /system/priv-app/PrebuiltKeep.odex
rm -rf /system/priv-app/PrebuiltKeepStub
rm -rf /system/priv-app/PrebuiltKeepStub.apk
rm -rf /system/priv-app/PrebuiltKeepStub.odex
rm -rf /system/priv-app/PrebuiltNewsWeather
rm -rf /system/priv-app/PrebuiltNewsWeather.apk
rm -rf /system/priv-app/PrebuiltNewsWeather.odex
rm -rf /system/priv-app/PrintSpooler
rm -rf /system/priv-app/PrintSpooler.apk
rm -rf /system/priv-app/PrintSpooler.odex
rm -rf /system/priv-app/QuickOffice
rm -rf /system/priv-app/QuickOffice.apk
rm -rf /system/priv-app/QuickOffice.odex
rm -rf /system/priv-app/QuickSearchBox
rm -rf /system/priv-app/QuickSearchBox.apk
rm -rf /system/priv-app/QuickSearchBox.odex
rm -rf /system/priv-app/SettingsGoogle
rm -rf /system/priv-app/SettingsGoogle.apk
rm -rf /system/priv-app/SettingsGoogle.odex
rm -rf /system/priv-app/SetupWizard
rm -rf /system/priv-app/SetupWizard.apk
rm -rf /system/priv-app/SetupWizard.odex
rm -rf /system/priv-app/StorageManagerGoogle
rm -rf /system/priv-app/StorageManagerGoogle.apk
rm -rf /system/priv-app/StorageManagerGoogle.odex
rm -rf /system/priv-app/Street
rm -rf /system/priv-app/Street.apk
rm -rf /system/priv-app/Street.odex
rm -rf /system/priv-app/SystemUIGoogle
rm -rf /system/priv-app/SystemUIGoogle.apk
rm -rf /system/priv-app/SystemUIGoogle.odex
rm -rf /system/priv-app/TagGoogle
rm -rf /system/priv-app/TagGoogle.apk
rm -rf /system/priv-app/TagGoogle.odex
rm -rf /system/priv-app/Talk
rm -rf /system/priv-app/Talk.apk
rm -rf /system/priv-app/Talk.odex
rm -rf /system/priv-app/talkback
rm -rf /system/priv-app/talkback.apk
rm -rf /system/priv-app/talkback.odex
rm -rf /system/priv-app/TranslatePrebuilt
rm -rf /system/priv-app/TranslatePrebuilt.apk
rm -rf /system/priv-app/TranslatePrebuilt.odex
rm -rf /system/priv-app/Turbo
rm -rf /system/priv-app/Turbo.apk
rm -rf /system/priv-app/Turbo.odex
rm -rf /system/priv-app/Tycho
rm -rf /system/priv-app/Tycho.apk
rm -rf /system/priv-app/Tycho.odex
rm -rf /system/priv-app/Velvet
rm -rf /system/priv-app/Velvet.apk
rm -rf /system/priv-app/Velvet.odex
rm -rf /system/priv-app/Velvet_update
rm -rf /system/priv-app/Velvet_update.apk
rm -rf /system/priv-app/Velvet_update.odex
rm -rf /system/priv-app/Vending
rm -rf /system/priv-app/Vending.apk
rm -rf /system/priv-app/Vending.odex
rm -rf /system/priv-app/Videos
rm -rf /system/priv-app/Videos.apk
rm -rf /system/priv-app/Videos.odex
rm -rf /system/priv-app/VoiceSearch
rm -rf /system/priv-app/VoiceSearch.apk
rm -rf /system/priv-app/VoiceSearch.odex
rm -rf /system/priv-app/VoiceSearchStub
rm -rf /system/priv-app/VoiceSearchStub.apk
rm -rf /system/priv-app/VoiceSearchStub.odex
rm -rf /system/priv-app/Wallet
rm -rf /system/priv-app/Wallet.apk
rm -rf /system/priv-app/Wallet.odex
rm -rf /system/priv-app/WallpaperPickerGooglePrebuilt
rm -rf /system/priv-app/WallpaperPickerGooglePrebuilt.apk
rm -rf /system/priv-app/WallpaperPickerGooglePrebuilt.odex
rm -rf /system/priv-app/WallpapersBReel2017
rm -rf /system/priv-app/WallpapersBReel2017.apk
rm -rf /system/priv-app/WallpapersBReel2017.odex
rm -rf /system/priv-app/WebViewGoogle
rm -rf /system/priv-app/WebViewGoogle.apk
rm -rf /system/priv-app/WebViewGoogle.odex
rm -rf /system/priv-app/WebViewStub
rm -rf /system/priv-app/WebViewStub.apk
rm -rf /system/priv-app/WebViewStub.odex
rm -rf /system/priv-app/YouTube
rm -rf /system/priv-app/YouTube.apk
rm -rf /system/priv-app/YouTube.odex
rm -rf /system/tts
rm -rf /system/usr/srec
rm -rf /system/vendor/lib/libfrsdk.so
rm -rf /system/vendor/lib64/libfrsdk.so
rm -rf /system/vendor/pittpatt
